### ISSUE TITLE
Check Redis configuration

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/tech-and-check-alerts#232]
We get a lot of the following error while the scrapers are running:

```
[0] BRPOPLPUSH ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[0]     at parseError (/data/repos/tech-and-check-alerts/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
[0]     at parseType (/data/repos/tech-and-check-alerts/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14) {
[0]   command: {
[0]     name: 'brpoplpush',
[0]     args: [
[0]       'bull:helloWorldCrawler:wait',
[0]       'bull:helloWorldCrawler:active',
[0]       '5'
[0]     ]
[0]   }
[0] }
```

Unsure if this is a permissions error, some sort of race condition, or… something else, but we should look into it!

**Comment by reefdog** [comment]
Hrm. Seeing a whole lot of this in `/var/log/redis/redis-server.log` since yesterday's changes:

```
23372:M 13 Sep 16:11:29.046 * 1 changes in 900 seconds. Saving...
23372:M 13 Sep 16:11:29.065 * Background saving started by pid 11917
11917:C 13 Sep 16:11:29.065 # Failed opening the RDB file dump.rdb (in server root dir /data/redis) for saving: Read-only file system
23372:M 13 Sep 16:11:29.166 # Background saving error
```

That's… not true. It's not a read-only file system, and both `/data/redis` and `/data/redis/dump.rdb` are owned by `redis:redis` and `-rw-rw----` (660), matching their original permissions. I'll look into it…

**Comment by reefdog** [comment]
Figured it out, [thanks to SO](https://serverfault.com/questions/942328/redis-reports-read-only-filesystem-but-it-isnt). Since I changed the default Redis output directory, I needed to give the Redis service system-controlled permissions to write to this directory. What a strange stricture.

**Comment by reefdog** [comment]
An interesting warning from the redis startup:

```
12438:M 13 Sep 16:23:42.836 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
```

**Comment by reefdog** [comment]
@slifty @cguess Do y'all think we can close this? It was basically a tracking issue for resolving our configuration-related Redis problems, and things seem to be trucking along. If we surface more problems, they should likely be new issues, yeah?

**Comment by slifty** [comment]
Yep sounds reasonable to me
